version: "3.8"

services:
  client-portal-dev:
    container_name: client-portal-dev
    image: client-portal-dev
    build:
      context: .
      target: development
    volumes:
      - ./app:/app/app
      - ./server:/app/server
    networks:
      - node-network
    ports:
      - 8080:3000

networks:
  node-network:
    external: true
